[[themes]]
name = "Afterglow Red"

[themes.palette]
background = "#202020"
foreground = "#ffffff"
black = "#111111"
red = "#AC4142"
green = "#AC4142"
yellow = "#ff7700"
blue = "#AC4142"
magenta = "#AC4142"
cyan = "#AC4142"
white = "#999999"
bright_black = "#333333"
bright_red = "#AC4142"
bright_green = "#AC4142"
bright_yellow = "#ff7700"
bright_blue = "#AC4142"
bright_magenta = "#AC4142"
bright_cyan = "#AC4142"
bright_white = "#ffffff"

[themes.component_style]
selection = { bg = "#333333", modifiers = ["Bold"] }
block_title = { fg = "#AC4142", modifiers = ["Bold"] }
playback_track = { fg = "#ffffff", modifiers = ["Bold"] }
playback_album = { fg = "#AC4142" }
playback_metadata = { fg = "#666666" }
playback_progress_bar = { bg = "#333333", fg = "#AC4142" }
current_playing = { fg = "#AC4142", modifiers = ["Bold"] }
page_desc = { fg = "#AC4142", modifiers = ["Bold"] }
table_header = { fg = "#999999", modifiers = ["Bold"] }
border = { fg = "#333333" }
playback_status = { fg = "#AC4142", modifiers = ["Bold"] }
playback_artists = { fg = "#AC4142", modifiers = ["Bold"] }
playlist_desc = { fg = "#666666" }

[[themes]]
name = "Afterglow Yellow"

[themes.palette]
background = "#202020"
foreground = "#ffffff"
black = "#111111"
red = "#E5B566"
green = "#E5B566"
yellow = "#ff7700"
blue = "#E5B566"
magenta = "#E5B566"
cyan = "#E5B566"
white = "#999999"
bright_black = "#333333"
bright_red = "#E5B566"
bright_green = "#E5B566"
bright_yellow = "#ff7700"
bright_blue = "#E5B566"
bright_magenta = "#E5B566"
bright_cyan = "#E5B566"
bright_white = "#ffffff"

[themes.component_style]
selection = { bg = "#333333", modifiers = ["Bold"] }
block_title = { fg = "#E5B566", modifiers = ["Bold"] }
playback_track = { fg = "#ffffff", modifiers = ["Bold"] }
playback_album = { fg = "#E5B566" }
playback_metadata = { fg = "#666666" }
playback_progress_bar = { bg = "#333333", fg = "#E5B566" }
current_playing = { fg = "#E5B566", modifiers = ["Bold"] }
page_desc = { fg = "#E5B566", modifiers = ["Bold"] }
table_header = { fg = "#999999", modifiers = ["Bold"] }
border = { fg = "#333333" }
playback_status = { fg = "#E5B566", modifiers = ["Bold"] }
playback_artists = { fg = "#E5B566", modifiers = ["Bold"] }
playlist_desc = { fg = "#666666" }

[[themes]]
name = "Afterglow Blue"

[themes.palette]
background = "#202020"
foreground = "#ffffff"
black = "#111111"
red = "#6C99BA"
green = "#6C99BA"
yellow = "#ff7700"
blue = "#6C99BA"
magenta = "#6C99BA"
cyan = "#6C99BA"
white = "#999999"
bright_black = "#333333"
bright_red = "#6C99BA"
bright_green = "#6C99BA"
bright_yellow = "#ff7700"
bright_blue = "#6C99BA"
bright_magenta = "#6C99BA"
bright_cyan = "#6C99BA"
bright_white = "#ffffff"

[themes.component_style]
selection = { bg = "#333333", modifiers = ["Bold"] }
block_title = { fg = "#6C99BA", modifiers = ["Bold"] }
playback_track = { fg = "#ffffff", modifiers = ["Bold"] }
playback_album = { fg = "#6C99BA" }
playback_metadata = { fg = "#666666" }
playback_progress_bar = { bg = "#333333", fg = "#6C99BA" }
current_playing = { fg = "#6C99BA", modifiers = ["Bold"] }
page_desc = { fg = "#6C99BA", modifiers = ["Bold"] }
table_header = { fg = "#999999", modifiers = ["Bold"] }
border = { fg = "#333333" }
playback_status = { fg = "#6C99BA", modifiers = ["Bold"] }
playback_artists = { fg = "#6C99BA", modifiers = ["Bold"] }
playlist_desc = { fg = "#666666" }

[[themes]]
name = "Afterglow Green"

[themes.palette]
background = "#202020"
foreground = "#ffffff"
black = "#111111"
red = "#7E8D50"
green = "#7E8D50"
yellow = "#ff7700"
blue = "#7E8D50"
magenta = "#7E8D50"
cyan = "#7E8D50"
white = "#999999"
bright_black = "#333333"
bright_red = "#7E8D50"
bright_green = "#7E8D50"
bright_yellow = "#ff7700"
bright_blue = "#7E8D50"
bright_magenta = "#7E8D50"
bright_cyan = "#7E8D50"
bright_white = "#ffffff"

[themes.component_style]
selection = { bg = "#333333", modifiers = ["Bold"] }
block_title = { fg = "#7E8D50", modifiers = ["Bold"] }
playback_track = { fg = "#ffffff", modifiers = ["Bold"] }
playback_album = { fg = "#7E8D50" }
playback_metadata = { fg = "#666666" }
playback_progress_bar = { bg = "#333333", fg = "#7E8D50" }
current_playing = { fg = "#7E8D50", modifiers = ["Bold"] }
page_desc = { fg = "#7E8D50", modifiers = ["Bold"] }
table_header = { fg = "#999999", modifiers = ["Bold"] }
border = { fg = "#333333" }
playback_status = { fg = "#7E8D50", modifiers = ["Bold"] }
playback_artists = { fg = "#7E8D50", modifiers = ["Bold"] }
playlist_desc = { fg = "#666666" }

[[themes]]
name = "Afterglow Magenta"

[themes.palette]
background = "#202020"
foreground = "#ffffff"
black = "#111111"
red = "#9E4E85"
green = "#9E4E85"
yellow = "#ff7700"
blue = "#9E4E85"
magenta = "#9E4E85"
cyan = "#9E4E85"
white = "#999999"
bright_black = "#333333"
bright_red = "#9E4E85"
bright_green = "#9E4E85"
bright_yellow = "#ff7700"
bright_blue = "#9E4E85"
bright_magenta = "#9E4E85"
bright_cyan = "#9E4E85"
bright_white = "#ffffff"

[themes.component_style]
selection = { bg = "#333333", modifiers = ["Bold"] }
block_title = { fg = "#9E4E85", modifiers = ["Bold"] }
playback_track = { fg = "#ffffff", modifiers = ["Bold"] }
playback_album = { fg = "#9E4E85" }
playback_metadata = { fg = "#666666" }
playback_progress_bar = { bg = "#333333", fg = "#9E4E85" }
current_playing = { fg = "#9E4E85", modifiers = ["Bold"] }
page_desc = { fg = "#9E4E85", modifiers = ["Bold"] }
table_header = { fg = "#999999", modifiers = ["Bold"] }
border = { fg = "#333333" }
playback_status = { fg = "#9E4E85", modifiers = ["Bold"] }
playback_artists = { fg = "#9E4E85", modifiers = ["Bold"] }
playlist_desc = { fg = "#666666" }

[[themes]]
name = "Afterglow Cyan"

[themes.palette]
background = "#202020"
foreground = "#ffffff"
black = "#111111"
red = "#7DD5CF"
green = "#7DD5CF"
yellow = "#ff7700"
blue = "#7DD5CF"
magenta = "#7DD5CF"
cyan = "#7DD5CF"
white = "#999999"
bright_black = "#333333"
bright_red = "#7DD5CF"
bright_green = "#7DD5CF"
bright_yellow = "#ff7700"
bright_blue = "#7DD5CF"
bright_magenta = "#7DD5CF"
bright_cyan = "#7DD5CF"
bright_white = "#ffffff"

[themes.component_style]
selection = { bg = "#333333", modifiers = ["Bold"] }
block_title = { fg = "#7DD5CF", modifiers = ["Bold"] }
playback_track = { fg = "#ffffff", modifiers = ["Bold"] }
playback_album = { fg = "#7DD5CF" }
playback_metadata = { fg = "#666666" }
playback_progress_bar = { bg = "#333333", fg = "#7DD5CF" }
current_playing = { fg = "#7DD5CF", modifiers = ["Bold"] }
page_desc = { fg = "#7DD5CF", modifiers = ["Bold"] }
table_header = { fg = "#999999", modifiers = ["Bold"] }
border = { fg = "#333333" }
playback_status = { fg = "#7DD5CF", modifiers = ["Bold"] }
playback_artists = { fg = "#7DD5CF", modifiers = ["Bold"] }
playlist_desc = { fg = "#666666" }

[[themes]]
name = "Afterglow Orange (custom)"

[themes.palette]
background = "#202020"
foreground = "#ffffff"
black = "#111111"
red = "#cc6b53"
green = "#cc6b53"
yellow = "#ff7700"
blue = "#cc6b53"
magenta = "#cc6b53"
cyan = "#cc6b53"
white = "#999999"
bright_black = "#333333"
bright_red = "#cc6b53"
bright_green = "#cc6b53"
bright_yellow = "#ff7700"
bright_blue = "#cc6b53"
bright_magenta = "#cc6b53"
bright_cyan = "#cc6b53"
bright_white = "#ffffff"

[themes.component_style]
selection = { bg = "#333333", modifiers = ["Bold"] }
block_title = { fg = "#cc6b53", modifiers = ["Bold"] }
playback_track = { fg = "#ffffff", modifiers = ["Bold"] }
playback_album = { fg = "#cc6b53" }
playback_metadata = { fg = "#666666" }
playback_progress_bar = { bg = "#333333", fg = "#cc6b53" }
current_playing = { fg = "#cc6b53", modifiers = ["Bold"] }
page_desc = { fg = "#cc6b53", modifiers = ["Bold"] }
table_header = { fg = "#999999", modifiers = ["Bold"] }
border = { fg = "#333333" }
playback_status = { fg = "#cc6b53", modifiers = ["Bold"] }
playback_artists = { fg = "#cc6b53", modifiers = ["Bold"] }
playlist_desc = { fg = "#666666" }